# Site settings
title: "News-First.com"
description: "New and News Worthy"
baseurl: ""
url: "http://news-first.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  
